import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";
import SmoothScrollProvider from "@/components/provider/SmoothScrollprovider";
import { QueryClientProvider } from "@/components/provider/QueryClientProvider";
import AuthSessionProvider from "@/components/provider/AuthSessionProvider";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Valoura | TRAVEL",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/fav.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>
        <NextTopLoader color="#CD9B46" height={3} showSpinner={false} />
        <QueryClientProvider>
          <SmoothScrollProvider>
            <AuthSessionProvider>{children}</AuthSessionProvider>
          </SmoothScrollProvider>
          <Toaster position="top-right" richColors closeButton />
        </QueryClientProvider>
      </body>
    </html>
  );
}
